<a href="https://colab.research.google.com/github/Siddhesh-3/Python/blob/main/udemy/Numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np

In [ ]:
my_list = [1,2,3,4]

my_arr = np.asarray(my_list)
print(my_arr)
print(my_arr.dtype)
print(my_arr.shape)

[1 2 3 4]
int64
(4,)


In [ ]:
np_array = np.ones((3,5), dtype  = int)
print(np_array)

np_range = np.arange(start = 1 , step = 3 , stop = 20)
print(np_range)

np_range2 = np.linspace(start = 2  , stop = 20 , num = 5)
print(np_range2)

np_random = np.random.random((2,5))
print(np_random)

[[1 1 1 1 1]
 [1 1 1 1 1]
 [1 1 1 1 1]]
[ 1  4  7 10 13 16 19]
[ 2.   6.5 11.  15.5 20. ]
[[0.70197346 0.43945857 0.57946877 0.26026153 0.22897712]
 [0.08190968 0.21973256 0.4564247  0.2952024  0.27831894]]


In [ ]:
#ex
import numpy as np
np_arr = np.arange(3 , 10)
print(np_arr)



[3 4 5 6 7 8 9]


In [ ]:
#Reshaping

import numpy as np

my_arr = np.arange(20)
print("normal array :\n\n",my_arr)
my_reshaped_arr = np.reshape(my_arr ,(5,4))
print("Reshaped array : \n\n", my_reshaped_arr)

normal array :

 [ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]
Reshaped array : 

 [[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]
 [16 17 18 19]]


In [ ]:
import numpy as np

my_arr = np.arange(20)
print(my_arr)
my_reshaped_arr = np.reshape(my_arr ,(5,4), order = "F")
print(my_reshaped_arr)



[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]
[[ 0  5 10 15]
 [ 1  6 11 16]
 [ 2  7 12 17]
 [ 3  8 13 18]
 [ 4  9 14 19]]


In [ ]:
#array into list
my_list = list(my_arr)
my_list[1] = 5
my_arr[1] = 6
print(my_list[1])
print(my_arr[1])



5
6


In [ ]:
my_list_reshaped = list(my_reshaped_arr)

print(my_reshaped_arr[0,1])
print(my_list_reshaped[0],[1])

5
[ 0  5 10 15] [1]


In [ ]:
import numpy as np
np_arr =  np.arange( 2 , 14 )

np_reshaped = np.reshape(np_arr , (3,4) )

np_reshaped[1,0] = 20
print(np_reshaped)

[[ 2  3  4  5]
 [20  7  8  9]
 [10 11 12 13]]


In [ ]:
#Slicing and Coping

In [ ]:
import numpy as np
my_list = [[1,2,3],[2,3,8],[1,3,7]]
np_arr = np.array(my_list)

## [start:end ,start:end]

print(np_arr[1:2,2])

[8]


In [ ]:
#copy array to do not change original one
import numpy as np

np_arr = np.array([[1,2,3],
                   [2,3,8],
                   [1,3,7]])
np_subarray = np_arr[1:2,0:]
print(np_subarray,"\n")
np_subarray[0,1] = 10

print(np_arr ,"\n") #both are modify here 
print(np_subarray)  #both are modify here 


[[2 3 8]] 

[[ 1  2  3]
 [ 2 10  8]
 [ 1  3  7]] 

[[ 2 10  8]]


In [ ]:
import numpy as np

np.random.seed(0)
np_rand = np.random.random((3,3))
print(np_rand,"\n")

np_copy_arr = np.copy(np_rand[0:3,1]) #0:3 row ,3:column
print(np_copy_arr,"\n")

np_copy_arr[0] = 1000
print(np_copy_arr,"\n")

print(np_rand)

[[0.5488135  0.71518937 0.60276338]
 [0.54488318 0.4236548  0.64589411]
 [0.43758721 0.891773   0.96366276]] 

[0.71518937 0.4236548  0.891773  ] 

[1.00000000e+03 4.23654799e-01 8.91773001e-01] 

[[0.5488135  0.71518937 0.60276338]
 [0.54488318 0.4236548  0.64589411]
 [0.43758721 0.891773   0.96366276]]


In [ ]:
np_arr = np.array( [10 , 21 , 5 , 11 ] )
np_sub_arr = np_arr[0:2
np_sub_arr[0:2] = [ 2 , 3 ]
print(np_arr)

[ 2  3  5 11]


In [ ]:
#Insert Append and Delete

In [ ]:
import numpy as np

np_arr = np.array([[1,2],[5,2]])
np_arr2 = np.insert( np_arr,1,[[5,3],[3,4]], axis = 1) #axis = 1 for row and 0 for colomun
print(np_arr2)

[[1 5 3 2]
 [5 3 4 2]]


In [ ]:
#

Insert,Append ,Delete in Numpy

In [4]:
#Insert
import numpy as np

np_arr = np.array([[1,2],[6,8]])
print(np_arr,"\n")

np_arr = np.insert(arr = np_arr , obj = 1 , values = [3,4] , axis = 0)
#axis = 1 for row and 0 for colomun
print(np_arr)

[[1 2]
 [6 8]] 

[[1 2]
 [3 4]
 [6 8]]


In [7]:
#Append
#covert array in 1D then append
np_arr_append = np.append(arr = np_arr ,values = [0,9])
# here when we insert value in one dimenstion [1,2] value cant insert using axis
#because original array is one dimentional ,and not add obj position  it directly append at end
print(np_arr_append)

[1 2 3 4 6 8 0 9]


In [8]:
np_arr_append1 = np.append(arr = np_arr ,values = [[0,9],[2,5]], axis = 0)
#here we pass two dimentional array then it works with axis we give axis = 0 
#then array append at end of column
print(np_arr_append1)

[[1 2]
 [3 4]
 [6 8]
 [0 9]
 [2 5]]


In [19]:
#Delete
np_new_array = [[1,5],[8,6]]
np_arr_delete = np.delete(arr = np_new_array , obj = 1 , axis = 0) 
#when axis is 1 it delete element in index 1 at column
#when axis is 0 it delete element in index 1 at row
print(np_arr_delete)

[[1 5]]


In [28]:
import numpy as np
np_arr = np.array( [[ 20 , 14] , [ 31 , 41] , [ 941 , 678] , [1468 , 121]] )
 
np_copy1 = np_arr.copy()
np_copy2 = np_arr.copy()
np_copy3 = np_arr.copy()
 
np_copy1 = np.append( np_copy1 , [ 3,4,5 ] )
 
np_copy2 = np.insert(arr =  np_copy2 ,obj = 1 ,values = [ [15,21] , [41,93 ] ] , axis = 0 )
 
np_copy3 = np.delete(np_copy3 , obj = 0 , axis = 0)

print(np_copy1,"\n")
print(np_copy2,"\n")
print(np_copy3,"\n")


[  20   14   31   41  941  678 1468  121    3    4    5] 

[[  20   14]
 [  15   21]
 [  41   93]
 [  31   41]
 [ 941  678]
 [1468  121]] 

[[  31   41]
 [ 941  678]
 [1468  121]] 



In [30]:
import numpy as np 

np_arr = np.array([[1,5,3],[4,1,6],[2,4,10]])

np_cond = np_arr[np_arr > 3]

print(np_cond)

print(np_arr > 3)

[ 5  4  6  4 10]
[[False  True False]
 [ True False  True]
 [False  True  True]]


In [ ]:
#BroadCasting

#much faster than for loops
#doesn't create new copy in memory

#One of dimenstion 1

#works with a * b where row and column is equal

In [33]:
import numpy as np 

np_arr = np.array([[2,3],[4,6]])

np_arr_broad = np_arr * 5

print(np_arr_broad)

[[10 15]
 [20 30]]


In [35]:
np_new_broad = np_arr * np_arr_broad
print(np_new_broad)

[[ 20  45]
 [ 80 180]]
